import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';

dotenv.config();

const supabase = createClient(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_SECRET_KEY!
);

async function main() {
  console.log('🌱 Seeding database...');

  // Países
  const countries = [
    {
      name: 'Polônia',
      official_name: 'Republic of Poland',
      iso_code: 'PL',
      iso3: 'POL',
      flag: '🇵🇱',
      continent: 'Europe',
      region: 'Eastern Europe',
      currency: 'PLN',
      language: 'Polish',
      population: 38000000,
      capital: 'Warsaw',
      timezone: 'Europe/Warsaw',
    },
    {
      name: 'Portugal',
      official_name: 'Portuguese Republic',
      iso_code: 'PT',
      iso3: 'PRT',
      flag: '🇵🇹',
      continent: 'Europe',
      region: 'Southern Europe',
      currency: 'EUR',
      language: 'Portuguese',
      population: 10300000,
      capital: 'Lisbon',
      timezone: 'Europe/Lisbon',
    },
    {
      name: 'Espanha',
      official_name: 'Kingdom of Spain',
      iso_code: 'ES',
      iso3: 'ESP',
      flag: '🇪🇸',
      continent: 'Europe',
      region: 'Southern Europe',
      currency: 'EUR',
      language: 'Spanish',
      population: 47400000,
      capital: 'Madrid',
      timezone: 'Europe/Madrid',
    },
    {
      name: 'Irlanda',
      official_name: 'Republic of Ireland',
      iso_code: 'IE',
      iso3: 'IRL',
      flag: '🇮🇪',
      continent: 'Europe',
      region: 'Northern Europe',
      currency: 'EUR',
      language: 'English',
      population: 5100000,
      capital: 'Dublin',
      timezone: 'Europe/Dublin',
    },
    {
      name: 'Canadá',
      official_name: 'Canada',
      iso_code: 'CA',
      iso3: 'CAN',
      flag: '🇨🇦',
      continent: 'North America',
      region: 'Northern America',
      currency: 'CAD',
      language: 'English/French',
      population: 39000000,
      capital: 'Ottawa',
      timezone: 'America/Toronto',
    },
    {
      name: 'Chile',
      official_name: 'Republic of Chile',
      iso_code: 'CL',
      iso3: 'CHL',
      flag: '🇨🇱',
      continent: 'South America',
      region: 'South America',
      currency: 'CLP',
      language: 'Spanish',
      population: 19600000,
      capital: 'Santiago',
      timezone: 'America/Santiago',
    },
    {
      name: 'Alemanha',
      official_name: 'Federal Republic of Germany',
      iso_code: 'DE',
      iso3: 'DEU',
      flag: '🇩🇪',
      continent: 'Europe',
      region: 'Western Europe',
      currency: 'EUR',
      language: 'German',
      population: 83200000,
      capital: 'Berlin',
      timezone: 'Europe/Berlin',
    },
    {
      name: 'Austrália',
      official_name: 'Commonwealth of Australia',
      iso_code: 'AU',
      iso3: 'AUS',
      flag: '🇦🇺',
      continent: 'Oceania',
      region: 'Australia and New Zealand',
      currency: 'AUD',
      language: 'English',
      population: 26000000,
      capital: 'Canberra',
      timezone: 'Australia/Sydney',
    },
  ];

  const { data: insertedCountries, error: countriesError } = await supabase
    .from('countries')
    .upsert(countries, { onConflict: 'iso_code' })
    .select();

  if (countriesError) {
    console.error('Error seeding countries:', countriesError);
    throw countriesError;
  }

  console.log(`✅ ${insertedCountries.length} countries seeded`);

  const countryMap = new Map(insertedCountries.map((c: any) => [c.iso_code, c.id]));

  // Cidades
  const cities = [
    {
      country_id: countryMap.get('PL'),
      name: 'Varsóvia',
      population: 1800000,
      latitude: 52.2297,
      longitude: 21.0122,
      airport: 'WAW',
      cost_index: 55.5,
      quality_of_life_score: 75.0,
      safety_score: 80.0,
      employment_score: 70.0,
    },
    {
      country_id: countryMap.get('PL'),
      name: 'Cracóvia',
      population: 780000,
      latitude: 50.0647,
      longitude: 19.9450,
      airport: 'KRK',
      cost_index: 50.0,
      quality_of_life_score: 78.0,
      safety_score: 82.0,
      employment_score: 68.0,
    },
    {
      country_id: countryMap.get('PT'),
      name: 'Lisboa',
      population: 550000,
      latitude: 38.7223,
      longitude: -9.1393,
      airport: 'LIS',
      cost_index: 65.0,
      quality_of_life_score: 82.0,
      safety_score: 85.0,
      employment_score: 75.0,
    },
    {
      country_id: countryMap.get('PT'),
      name: 'Porto',
      population: 240000,
      latitude: 41.1579,
      longitude: -8.6291,
      airport: 'OPO',
      cost_index: 58.0,
      quality_of_life_score: 80.0,
      safety_score: 86.0,
      employment_score: 70.0,
    },
    {
      country_id: countryMap.get('ES'),
      name: 'Madri',
      population: 3300000,
      latitude: 40.4168,
      longitude: -3.7038,
      airport: 'MAD',
      cost_index: 62.0,
      quality_of_life_score: 80.0,
      safety_score: 78.0,
      employment_score: 72.0,
    },
    {
      country_id: countryMap.get('IE'),
      name: 'Dublin',
      population: 1400000,
      latitude: 53.3498,
      longitude: -6.2603,
      airport: 'DUB',
      cost_index: 78.0,
      quality_of_life_score: 79.0,
      safety_score: 76.0,
      employment_score: 85.0,
    },
    {
      country_id: countryMap.get('CA'),
      name: 'Toronto',
      population: 2900000,
      latitude: 43.6532,
      longitude: -79.3832,
      airport: 'YYZ',
      cost_index: 75.0,
      quality_of_life_score: 84.0,
      safety_score: 82.0,
      employment_score: 82.0,
    },
    {
      country_id: countryMap.get('CL'),
      name: 'Santiago',
      population: 5700000,
      latitude: -33.4489,
      longitude: -70.6693,
      airport: 'SCL',
      cost_index: 48.0,
      quality_of_life_score: 72.0,
      safety_score: 65.0,
      employment_score: 68.0,
    },
    {
      country_id: countryMap.get('DE'),
      name: 'Berlim',
      population: 3700000,
      latitude: 52.5200,
      longitude: 13.4050,
      airport: 'BER',
      cost_index: 68.0,
      quality_of_life_score: 83.0,
      safety_score: 78.0,
      employment_score: 80.0,
    },
    {
      country_id: countryMap.get('AU'),
      name: 'Sydney',
      population: 5300000,
      latitude: -33.8688,
      longitude: 151.2093,
      airport: 'SYD',
      cost_index: 82.0,
      quality_of_life_score: 86.0,
      safety_score: 84.0,
      employment_score: 80.0,
    },
  ];

  const { error: citiesError } = await supabase.from('cities').insert(cities);
  if (citiesError) console.error('Error seeding cities:', citiesError);
  else console.log(`✅ ${cities.length} cities seeded`);

  // Vistos
  const visaRoutes = [
    {
      country_id: countryMap.get('PL'),
      name: 'Poland Work Visa (Type D)',
      category: 'work',
      description: 'Visto nacional de trabalho para profissionais com oferta de emprego na Polônia.',
      min_income: 4000,
      experience_requirement: 2,
      language_requirement: 'Polish B1 ou English B2 (varia por empregador)',
      required_documents: ['passaporte', 'contrato de trabalho', 'comprovante de alojamento', 'seguro saúde'],
      fee: 440,
      fee_currency: 'PLN',
      processing_time: '2-3 meses',
      duration: '1-3 anos',
      renewable: true,
      allows_permanent_residence: true,
      allows_citizenship: true,
      official_source: 'Polish Ministry of Foreign Affairs',
      official_url: 'https://www.gov.pl/web/diplomacy',
      last_verified: new Date().toISOString(),
    },
    {
      country_id: countryMap.get('PT'),
      name: 'D7 Visa — Passive Income',
      category: 'passive_income',
      description: 'Visto para pessoas com renda passiva (aposentadoria, investimentos, trabalho remoto).',
      min_income: 760,
      fee: 90,
      fee_currency: 'EUR',
      processing_time: '2-4 meses',
      duration: '2 anos',
      renewable: true,
      allows_permanent_residence: true,
      allows_citizenship: true,
      official_source: 'AIMA Portugal',
      official_url: 'https://aima.gov.pt',
      last_verified: new Date().toISOString(),
    },
    {
      country_id: countryMap.get('PT'),
      name: 'Digital Nomad Visa',
      category: 'digital_nomad',
      description: 'Visto para trabalhadores remotos com renda comprovada.',
      min_income: 3040,
      fee: 90,
      fee_currency: 'EUR',
      processing_time: '1-3 meses',
      duration: '1 ano',
      renewable: true,
      allows_permanent_residence: true,
      allows_citizenship: true,
      official_source: 'AIMA Portugal',
      official_url: 'https://aima.gov.pt',
      last_verified: new Date().toISOString(),
    },
    {
      country_id: countryMap.get('ES'),
      name: 'Digital Nomad Visa (Spain)',
      category: 'digital_nomad',
      description: 'Visto para nômades digitais trabalhando remotamente para empresas fora da Espanha.',
      min_income: 2520,
      fee: 80,
      fee_currency: 'EUR',
      processing_time: '1-3 meses',
      duration: '1-3 anos',
      renewable: true,
      allows_permanent_residence: true,
      allows_citizenship: true,
      official_source: 'Ministerio de Asuntos Exteriores',
      official_url: 'https://www.exteriores.gob.es',
      last_verified: new Date().toISOString(),
    },
    {
      country_id: countryMap.get('IE'),
      name: 'Critical Skills Employment Permit',
      category: 'skilled_worker',
      description: 'Permissão de trabalho para profissionais em áreas de alta demanda (TI, engenharia, saúde).',
      min_income: 38000,
      experience_requirement: 2,
      language_requirement: 'English (empregador pode exigir comprovação)',
      required_documents: ['passaporte', 'oferta de emprego', 'qualificações'],
      fee: 1000,
      fee_currency: 'EUR',
      processing_time: '6-8 semanas',
      duration: '2 anos',
      renewable: true,
      allows_permanent_residence: true,
      allows_citizenship: true,
      official_source: 'Department of Enterprise, Trade and Employment',
      official_url: 'https://enterprise.gov.ie',
      last_verified: new Date().toISOString(),
    },
    {
      country_id: countryMap.get('CA'),
      name: 'Express Entry — Federal Skilled Worker',
      category: 'skilled_worker',
      description: 'Sistema de pontos (CRS) para residência permanente baseado em idade, educação, experiência e idioma.',
      language_requirement: 'English ou French (IELTS/CELPIP/TEF)',
      experience_requirement: 1,
      required_documents: ['passaporte', 'teste de idioma', 'avaliação educacional (ECA)', 'comprovante de fundos'],
      fee: 1525,
      fee_currency: 'CAD',
      processing_time: '6 meses',
      duration: 'Residência permanente',
      renewable: false,
      allows_permanent_residence: true,
      allows_citizenship: true,
      official_source: 'IRCC Canada',
      official_url: 'https://www.canada.ca/en/immigration-refugees-citizenship.html',
      last_verified: new Date().toISOString(),
    },
    {
      country_id: countryMap.get('DE'),
      name: 'EU Blue Card',
      category: 'eu_blue_card',
      description: 'Para profissionais altamente qualificados com oferta de emprego e salário mínimo.',
      min_income: 45300,
      education_requirement: 'Diploma universitário reconhecido',
      fee: 100,
      fee_currency: 'EUR',
      processing_time: '1-3 meses',
      duration: '4 anos',
      renewable: true,
      allows_permanent_residence: true,
      allows_citizenship: true,
      official_source: 'Make it in Germany',
      official_url: 'https://www.make-it-in-germany.com',
      last_verified: new Date().toISOString(),
    },
    {
      country_id: countryMap.get('CL'),
      name: 'Visa Temporária de Trabalho',
      category: 'work',
      description: 'Visto temporário para estrangeiros com contrato de trabalho no Chile.',
      fee: 100,
      fee_currency: 'USD',
      processing_time: '1-2 meses',
      duration: '2 anos',
      renewable: true,
      allows_permanent_residence: true,
      allows_citizenship: true,
      official_source: 'Servicio Nacional de Migraciones Chile',
      official_url: 'https://serviciomigraciones.cl',
      last_verified: new Date().toISOString(),
    },
    {
      country_id: countryMap.get('AU'),
      name: 'Skilled Independent Visa (189)',
      category: 'skilled_worker',
      description: 'Visto de residência permanente por pontos para profissionais qualificados sem patrocínio.',
      experience_requirement: 3,
      language_requirement: 'English (IELTS 6+ ou equivalente)',
      fee: 4640,
      fee_currency: 'AUD',
      processing_time: '6-12 meses',
      duration: 'Residência permanente',
      renewable: false,
      allows_permanent_residence: true,
      allows_citizenship: true,
      official_source: 'Department of Home Affairs Australia',
      official_url: 'https://immi.homeaffairs.gov.au',
      last_verified: new Date().toISOString(),
    },
  ];

  const { error: visasError } = await supabase.from('visa_routes').insert(visaRoutes);
  if (visasError) console.error('Error seeding visas:', visasError);
  else console.log(`✅ ${visaRoutes.length} visa routes seeded`);

  // Custo de vida (valores estimados — fonte: agregação de dados públicos)
  const costOfLiving = [
    { country_id: countryMap.get('PL'), category: 'single', rent: 2500, food: 800, transport: 150, utilities: 300, internet: 50, health: 200, leisure: 300, average_salary: 6000, currency: 'PLN', source: 'Estimativa agregada', confidence: 'medium', retrieved_at: new Date().toISOString() },
    { country_id: countryMap.get('PT'), category: 'single', rent: 800, food: 300, transport: 50, utilities: 100, internet: 35, health: 80, leisure: 150, average_salary: 1800, currency: 'EUR', source: 'Estimativa agregada', confidence: 'medium', retrieved_at: new Date().toISOString() },
    { country_id: countryMap.get('ES'), category: 'single', rent: 900, food: 320, transport: 55, utilities: 120, internet: 35, health: 90, leisure: 160, average_salary: 2000, currency: 'EUR', source: 'Estimativa agregada', confidence: 'medium', retrieved_at: new Date().toISOString() },
    { country_id: countryMap.get('IE'), category: 'single', rent: 1600, food: 400, transport: 100, utilities: 150, internet: 50, health: 120, leisure: 200, average_salary: 3500, currency: 'EUR', source: 'Estimativa agregada', confidence: 'medium', retrieved_at: new Date().toISOString() },
    { country_id: countryMap.get('CA'), category: 'single', rent: 1800, food: 450, transport: 120, utilities: 160, internet: 70, health: 100, leisure: 220, average_salary: 4500, currency: 'CAD', source: 'Estimativa agregada', confidence: 'medium', retrieved_at: new Date().toISOString() },
    { country_id: countryMap.get('CL'), category: 'single', rent: 450000, food: 200000, transport: 40000, utilities: 80000, internet: 25000, health: 60000, leisure: 100000, average_salary: 1200000, currency: 'CLP', source: 'Estimativa agregada', confidence: 'medium', retrieved_at: new Date().toISOString() },
    { country_id: countryMap.get('DE'), category: 'single', rent: 1100, food: 350, transport: 80, utilities: 200, internet: 40, health: 100, leisure: 180, average_salary: 3800, currency: 'EUR', source: 'Estimativa agregada', confidence: 'medium', retrieved_at: new Date().toISOString() },
    { country_id: countryMap.get('AU'), category: 'single', rent: 2000, food: 500, transport: 150, utilities: 200, internet: 70, health: 120, leisure: 250, average_salary: 5500, currency: 'AUD', source: 'Estimativa agregada', confidence: 'medium', retrieved_at: new Date().toISOString() },
  ];

  const { error: costError } = await supabase.from('cost_of_living').insert(costOfLiving);
  if (costError) console.error('Error seeding cost of living:', costError);
  else console.log(`✅ ${costOfLiving.length} cost of living records seeded`);

  console.log('🎉 Database seeded successfully!');
}

main().catch((e) => {
  console.error('❌ Seed failed:', e);
  process.exit(1);
});