// Dados locais de fallback — usados quando a API não está disponível
export const FALLBACK_COUNTRIES = [
  {
    id: 'pl',
    name: 'Polônia',
    iso_code: 'PL',
    flag: '🇵🇱',
    continent: 'Europa',
    currency: 'PLN',
    population: 38000000,
    capital: 'Varsóvia',
    language: 'Polonês',
    costOfLiving: { rent: 2500, food: 800, transport: 150, utilities: 300, internet: 50, health: 200, leisure: 300, currency: 'PLN' },
    visas: [
      { name: 'Work Visa (Type D)', category: 'work', processingTime: '2-3 meses', renewable: true, allowsPR: true },
    ],
    cities: [
      { name: 'Varsóvia', population: 1800000, safetyScore: 80, qualityScore: 75 },
      { name: 'Cracóvia', population: 780000, safetyScore: 82, qualityScore: 78 },
    ],
  },
  {
    id: 'pt',
    name: 'Portugal',
    iso_code: 'PT',
    flag: '🇵🇹',
    continent: 'Europa',
    currency: 'EUR',
    population: 10300000,
    capital: 'Lisboa',
    language: 'Português',
    costOfLiving: { rent: 800, food: 300, transport: 50, utilities: 100, internet: 35, health: 80, leisure: 150, currency: 'EUR' },
    visas: [
      { name: 'D7 — Renda Passiva', category: 'passive_income', processingTime: '2-4 meses', renewable: true, allowsPR: true },
      { name: 'Digital Nomad Visa', category: 'digital_nomad', processingTime: '1-3 meses', renewable: true, allowsPR: true },
    ],
    cities: [
      { name: 'Lisboa', population: 550000, safetyScore: 85, qualityScore: 82 },
      { name: 'Porto', population: 240000, safetyScore: 86, qualityScore: 80 },
    ],
  },
  {
    id: 'es',
    name: 'Espanha',
    iso_code: 'ES',
    flag: '🇪🇸',
    continent: 'Europa',
    currency: 'EUR',
    population: 47400000,
    capital: 'Madri',
    language: 'Espanhol',
    costOfLiving: { rent: 900, food: 320, transport: 55, utilities: 120, internet: 35, health: 90, leisure: 160, currency: 'EUR' },
    visas: [
      { name: 'Digital Nomad Visa', category: 'digital_nomad', processingTime: '1-3 meses', renewable: true, allowsPR: true },
    ],
    cities: [
      { name: 'Madri', population: 3300000, safetyScore: 78, qualityScore: 80 },
    ],
  },
  {
    id: 'ie',
    name: 'Irlanda',
    iso_code: 'IE',
    flag: '🇮🇪',
    continent: 'Europa',
    currency: 'EUR',
    population: 5100000,
    capital: 'Dublin',
    language: 'Inglês',
    costOfLiving: { rent: 1600, food: 400, transport: 100, utilities: 150, internet: 50, health: 120, leisure: 200, currency: 'EUR' },
    visas: [
      { name: 'Critical Skills Employment Permit', category: 'skilled_worker', processingTime: '6-8 semanas', renewable: true, allowsPR: true },
    ],
    cities: [
      { name: 'Dublin', population: 1400000, safetyScore: 76, qualityScore: 79 },
    ],
  },
  {
    id: 'ca',
    name: 'Canadá',
    iso_code: 'CA',
    flag: '🇨🇦',
    continent: 'América do Norte',
    currency: 'CAD',
    population: 39000000,
    capital: 'Ottawa',
    language: 'Inglês/Francês',
    costOfLiving: { rent: 1800, food: 450, transport: 120, utilities: 160, internet: 70, health: 100, leisure: 220, currency: 'CAD' },
    visas: [
      { name: 'Express Entry — Federal Skilled Worker', category: 'skilled_worker', processingTime: '6 meses', renewable: false, allowsPR: true },
    ],
    cities: [
      { name: 'Toronto', population: 2900000, safetyScore: 82, qualityScore: 84 },
    ],
  },
  {
    id: 'cl',
    name: 'Chile',
    iso_code: 'CL',
    flag: '🇨🇱',
    continent: 'América do Sul',
    currency: 'CLP',
    population: 19600000,
    capital: 'Santiago',
    language: 'Espanhol',
    costOfLiving: { rent: 450000, food: 200000, transport: 40000, utilities: 80000, internet: 25000, health: 60000, leisure: 100000, currency: 'CLP' },
    visas: [
      { name: 'Visa Temporária de Trabalho', category: 'work', processingTime: '1-2 meses', renewable: true, allowsPR: true },
    ],
    cities: [
      { name: 'Santiago', population: 5700000, safetyScore: 65, qualityScore: 72 },
    ],
  },
  {
    id: 'de',
    name: 'Alemanha',
    iso_code: 'DE',
    flag: '🇩🇪',
    continent: 'Europa',
    currency: 'EUR',
    population: 83200000,
    capital: 'Berlim',
    language: 'Alemão',
    costOfLiving: { rent: 1100, food: 350, transport: 80, utilities: 200, internet: 40, health: 100, leisure: 180, currency: 'EUR' },
    visas: [
      { name: 'EU Blue Card', category: 'eu_blue_card', processingTime: '1-3 meses', renewable: true, allowsPR: true },
    ],
    cities: [
      { name: 'Berlim', population: 3700000, safetyScore: 78, qualityScore: 83 },
    ],
  },
  {
    id: 'au',
    name: 'Austrália',
    iso_code: 'AU',
    flag: '🇦🇺',
    continent: 'Oceania',
    currency: 'AUD',
    population: 26000000,
    capital: 'Canberra',
    language: 'Inglês',
    costOfLiving: { rent: 2000, food: 500, transport: 150, utilities: 200, internet: 70, health: 120, leisure: 250, currency: 'AUD' },
    visas: [
      { name: 'Skilled Independent Visa (189)', category: 'skilled_worker', processingTime: '6-12 meses', renewable: false, allowsPR: true },
    ],
    cities: [
      { name: 'Sydney', population: 5300000, safetyScore: 84, qualityScore: 86 },
    ],
  },
];